### ISSUE TITLE
Init local

### ISSUE THREAD

**Issue by IanaKhitsko** [OlgaYashan/tpps2#2]
https://github.com/OlgaYashan/tpps2/blob/63bd60ad3592695089384c71e52ad129c8e07bc2/City.cs#L89

please initialize local, even if it is used in the cycle only

**Comment by OlgaYashan** [comment]
Resolved here: https://github.com/OlgaYashan/tpps2/commit/654171035bab431c892bf0592d6abe2c9de42b34
