### ISSUE TITLE
Private member declaration

### ISSUE THREAD

**Issue by IanaKhitsko** [OlgaYashan/tpps2#3]
https://github.com/OlgaYashan/tpps2/blob/63bd60ad3592695089384c71e52ad129c8e07bc2/Eurozone.cs#L16

NumberOfNeighbours  - > numberOfNeighbours 
(it seems you use lower case for private members, just style issue)

**Comment by OlgaYashan** [comment]
Resolved here: https://github.com/OlgaYashan/tpps2/commit/d878f74c00b91e86802b5bedaedea0654bf7dd83
