### ISSUE TITLE
Can we remove flag ? 

### ISSUE THREAD

**Issue by IanaKhitsko** [OlgaYashan/tpps2#6]
https://github.com/OlgaYashan/tpps2/blob/63bd60ad3592695089384c71e52ad129c8e07bc2/Eurozone.cs#L113

                if (completeCityCount != currentCountry.Cities.Count)
                    return false;
}
return true;

??

**Comment by OlgaYashan** [comment]
Yes, https://github.com/OlgaYashan/tpps2/blob/master/Eurozone.cs
